name: "Pantheon Review Apps"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# You will also need to add the secrets used below to Dependabot secrets
# if you want this to successfully run in auto-created PRs.
permissions:
  deployments: write
  contents: read
  pull-requests: read

jobs:
  Drainpipe-Deploy-Pantheon-Multidev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: ./.github/actions/drainpipe/set-env

      - uses: ./.github/actions/drainpipe/setup-git
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com

      - uses: ./.github/actions/drainpipe/setup-ssh
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - uses: ./github/actions/drainpipe/pantheon/setup-terminus
        with:
          pantheon-token: ${{ secrets.PANTHEON_TERMINUS_TOKEN }}
          terminus-plugins: ${{ secrets.TERMINUS_PLUGINS }}

      - uses: php-actions/composer@v6

      - name: Build Project
        env:
          directory: /tmp/release
          remote:
          message:
          site:
        run: |
          composer install
          task build
          task snapshot:directory directory=/tmp/release

      - name: Deploy Pantheon Review App
        uses: ./.github/actions/drainpipe/pantheon/review
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terminus-token: ${{ secrets.PANTHEON_TERMINUS_TOKEN }}
          site-name: [site-name]
          commit-message: ${{ github.event.head_commit.message }}
