name: "Pantheon Review Apps"

on:
  pull_request:
    types: [labeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  deployments: write
  contents: read
  pull-requests: read

jobs:
  Drainpipe-Deploy-Pantheon-Multidev:
    if: contains(github.event.pull_request.labels.*.name, 'build multidev')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ github.workspace }}/.ddev/.drainpipe-composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - uses: ./.github/actions/drainpipe/set-env

      - uses: ./.github/actions/drainpipe/validate-terminus-timeout
        with:
          terminus_timeout_limit: ${{ vars.TERMINUS_TIMEOUT_LIMIT }}

      - name: Install and Start DDEV
        uses: ./.github/actions/drainpipe/ddev
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Build Project
        env:
          directory: /tmp/release
        run: |
          ddev composer install
          ddev task build
          ddev task snapshot:directory directory=/tmp/release

      - name: Deploy Pantheon Review App
        uses: ./.github/actions/drainpipe/pantheon/review
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terminus-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
          commit-message: ${{ github.sha }}
          site-name: ${{ vars.PANTHEON_SITE_NAME || secrets.PANTHEON_SITE_NAME }}
          lock-username: ${{ secrets.PANTHEON_REVIEW_USERNAME }}
          lock-password: ${{ secrets.PANTHEON_REVIEW_PASSWORD }}
          # set to "true" if you want to run the installer
          run-installer: ${{ secrets.PANTHEON_REVIEW_RUN_INSTALLER }}
          clone-from: ${{ vars.PANTHEON_CLONE_FROM || 'live' }}
          terminus-timeout-limit: ${{ env.TERMINUS_TIMEOUT_LIMIT }}
          skip-wipe-multidev: ${{ vars.PANTHEON_SKIP_WIPE_MULTIDEV }}
