name: "Clone Environment"
description: "Clones an Acquia Environment to another site"
inputs:
  source-environment:
    description: "Source environment i.e. the uuid or environment alias"
    required: true
  target-environment:
    description: "Target environment i.e. the uuid or environment alias"
    required: true
  api-key:
    description: "Acquia API Key"
    required: true
  api-secret:
    description: "Acquia API Secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone Environment
      env:
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_API_SECRET: ${{ inputs.api-secret }}
        INPUT_SOURCE_ENV: ${{ inputs.source-environment }}
        INPUT_TARGET_ENV: ${{ inputs.target-environment }}
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec "ACQUIA_API_KEY=$INPUT_API_KEY ACQUIA_API_SECRET=$INPUT_API_SECRET ./vendor/bin/task acquia:auth"
        drainpipe_exec "acli env:mirror --no-config --no-interaction $INPUT_SOURCE_ENV $INPUT_TARGET_ENV"
      shell: bash
