name: "Clone Environment"
description: "Clones an Acquia Environment to another site"
inputs:
  source-environment:
    description: "Source environment i.e. the uuid or environment alias"
    required: true
  target-environment:
    description: "Target environment i.e. the uuid or environment alias"
    required: true
  api-key:
    description: "Acquia API Key"
    required: true
  api-secret:
    description: "Acquia API Secret"
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone Environment
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec "ACQUIA_API_KEY=${ACQUIA_API_KEY} ACQUIA_API_SECRET=${ACQUIA_API_SECRET} ./vendor/bin/task acquia:auth"
        drainpipe_exec "acli env:mirror --no-config --no-interaction ${SOURCE_ENVIRONMENT} ${TARGET_ENVIRONMENT}"
      shell: bash
      env:
        ACQUIA_API_KEY: ${{ inputs.api-key }}
        ACQUIA_API_SECRET: ${{ inputs.api-secret }}
        SOURCE_ENVIRONMENT: ${{ inputs.source-environment }}
        TARGET_ENVIRONMENT: ${{ inputs.target-environment }}
