#!/usr/bin/env bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -euo pipefail

type="${1:-}"
if [[ -z "$type" ]]; then
  echo "Usage: $0 <service-type>" >&2
  exit 2
fi

# Install Taskfile
TASKFILE=$(cat ${TUGBOAT_ROOT}/vendor/lullabot/drainpipe/.taskfile)
sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d ${TASKFILE} -b /usr/local/bin

# Install YQ
YQ_VERSION=v4.50.1
wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq

# Ensure includes are not executed
yq -i 'del(."includes")' Taskfile.yml

# Execute the custom command
task "tugboat:${type}:init"
