name: "Update or Install Pantheon Site"
description: "Runs the Drupal updater or the site installer in a Pantheon environment"
inputs:
  site-name:
    description: "Pantheon site machine name"
    required: true
  run-installer:
    description: "Whether or not to run the Drupal site installer. Defaults to false."
    required: false
  environment:
    description: "The environment to run the updates or install in e.g. 'test'"
    required: true
  skip-workflow-wait:
    description: "When 'true', skip terminus workflow:wait. Use when the sync is already complete (e.g. triggered by Quicksilver)."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Update site on Pantheon
      env:
        INPUT_SITE_NAME: ${{ inputs.site-name }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_RUN_INSTALLER: ${{ inputs.run-installer }}
        INPUT_SKIP_WORKFLOW_WAIT: ${{ inputs.skip-workflow-wait }}
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        task pantheon:drupal-update \
          site="$INPUT_SITE_NAME" \
          environment="$INPUT_ENVIRONMENT" \
          skip_workflow_wait="$INPUT_SKIP_WORKFLOW_WAIT" \
          run_installer="$INPUT_RUN_INSTALLER"
      shell: bash
