name: "Update or Install Pantheon Site"
description: "Runs the Drupal updater or the site installer in a Pantheon environment"
inputs:
  site-name:
    description: "Pantheon site machine name"
    required: true
  run-installer:
    description: "Whether or not to run the Drupal site installer. Defaults to false."
    required: false
  environment:
    description: "The environment to run the updates or install in e.g. 'test'"
    required: true
  skip-workflow-wait:
    description: "When 'true', skip terminus workflow:wait. Use when the sync is already complete (e.g. triggered by Quicksilver)."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Update site on Pantheon
      env:
        INPUT_SITE_NAME: ${{ inputs.site-name }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_RUN_INSTALLER: ${{ inputs.run-installer }}
        INPUT_SKIP_WORKFLOW_WAIT: ${{ inputs.skip-workflow-wait }}
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        if [ "$INPUT_SKIP_WORKFLOW_WAIT" != "true" ]; then
          # Wait for Pantheon to sync.
          drainpipe_exec "terminus workflow:wait $INPUT_SITE_NAME.$INPUT_ENVIRONMENT"
        fi
        drainpipe_exec "terminus aliases --only $INPUT_SITE_NAME --yes"
        if [ "$INPUT_RUN_INSTALLER" == "true" ]; then
          drainpipe_exec "./vendor/bin/drush @$INPUT_SITE_NAME.$INPUT_ENVIRONMENT --yes site:install --existing-config"
        elif drainpipe_exec "./vendor/bin/task -l | grep '* update: '"; then
          drainpipe_exec "./vendor/bin/task update site=@$INPUT_SITE_NAME.$INPUT_ENVIRONMENT"
        else
          drainpipe_exec "./vendor/bin/task drupal:update site=@$INPUT_SITE_NAME.$INPUT_ENVIRONMENT"
        fi
      shell: bash
