name: "Update or Install Pantheon Site"
description: "Runs the Drupal updater or the site installer in a Pantheon environment"
inputs:
  site-name:
    description: "Pantheon site machine name"
    required: true
  run-installer:
    description: "Whether or not to run the Drupal site installer. Defaults to false."
    required: false
  environment:
    description: "The environment to run the updates or install in e.g. 'test'"
    required: true
  sleep:
    description: "The amount of time to wait before this step is run. Useful if you've just pushed code as it takes Pantheon time to sync. Default is 30"
    required: false
runs:
  using: "composite"
  steps:
    - name: Update site on Pantheon
      run: |
        # Wait for Pantheon to sync
        if [ "${{ inputs.sleep }}" != "" ]; then
          sleep ${{ inputs.sleep }}
        else
          sleep 30
        fi
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec "terminus aliases --only ${{ inputs.site-name }} --yes"
        if [ "${{ inputs.run-installer }}" == "true" ]; then
          drainpipe_exec "./vendor/bin/drush @${{ inputs.site-name }}.${{ inputs.environment }} --yes site:install --existing-config"
        else
          drainpipe_exec "./vendor/bin/task drupal:update site=@${{ inputs.site-name }}.${{ inputs.environment }}"
        fi
      shell: bash

