extends: default

ignore: |
  vendor/*
  drainpipe-dev/*

rules:
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 1
  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 1
  comments:
    min-spaces-from-content: 1
  document-start:
    present: false
  empty-lines:
    max: 1
  indentation:
    spaces: 2
  line-length: disable
  truthy: disable
