version: '3'

dotenv: ['.env']

includes:
  drupal: ./tasks/drupal.yml
  snapshot: ./tasks/snapshot.yml
  test: ./tasks/test.yml

tasks:
  default:
    desc: "Example command"
    cmds:
      - echo "Hello, world!"
