name: "Post comment with composer's package differences on the current GitHub PR"
description: 'Posts a comment with the composer-lock-diff output on the current GitHub PR'

runs:
  using: "composite"
  steps:
    - name: GitHub Script
      uses: actions/github-script@v6.1.1
      with:
        script: |
          const script = require('.github/actions/drainpipe/composer-lock-diff-comment/script.js');
          await script({github, context});
