#!/usr/bin/env bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -euo pipefail

MINIMAL=false
for arg in "$@"; do
  case "$arg" in
    --minimal) MINIMAL=true ;;
  esac
done

if [ "$MINIMAL" = "true" ]; then
  apt-get update -qq && apt-get install -y -qq git curl jq unzip
else
  apt-get update -qq && apt-get install -y -qq git curl jq unzip libfreetype6-dev libjpeg62-turbo-dev libpng-dev libwebp-dev
  docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
  docker-php-ext-install -j"$(nproc)" gd
  mkdir -p ~/.ssh && chmod 700 ~/.ssh
  echo "${ACQUIA_SSH_PRIVATE_KEY}" | base64 -d > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  git config --global user.name "Drainpipe Bot"
  git config --global user.email "no-reply@example.com"
fi

if ! command -v composer &>/dev/null; then
  COMPOSER_VERSION=2.9.5
  curl -sS "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" -o /usr/local/bin/composer
  chmod +x /usr/local/bin/composer
fi
