#!/usr/bin/env bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -euo pipefail

log() {
  printf '[setup-php] %s\n' "$*" >&2
}

MINIMAL=false
for arg in "$@"; do
  case "$arg" in
    --minimal) MINIMAL=true ;;
  esac
done

log "apt-get install git curl jq unzip"
apt-get update -qq && apt-get install -y -qq git curl jq unzip

if ! command -v composer &>/dev/null; then
  COMPOSER_VERSION=2.9.5
  log "composer not found; installing ${COMPOSER_VERSION} to /usr/local/bin/composer"
  curl -sS "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar" -o /usr/local/bin/composer
  chmod +x /usr/local/bin/composer
  log "composer installed: $(command -v composer)"
else
  log "composer already present: $(command -v composer) ($(composer --version 2>/dev/null | head -n1))"
fi

if [ "$MINIMAL" != "true" ]; then
  # install-php-extensions handles apt dependencies, configure flags, and
  # PECL vs built-in logic automatically for any extension name passed to it.
  # See https://github.com/mlocati/docker-php-extension-installer
  IPE_VERSION=2.7.14
  log "downloading install-php-extensions ${IPE_VERSION}"
  curl -sSLf "https://github.com/mlocati/docker-php-extension-installer/releases/download/${IPE_VERSION}/install-php-extensions" \
    -o /usr/local/bin/install-php-extensions
  chmod +x /usr/local/bin/install-php-extensions
  log "install-php-extensions ready at /usr/local/bin/install-php-extensions"

  # Detect PHP extensions declared in composer.json/composer.lock that are
  # missing from the current environment and install them automatically.
  # To identify extensions your project needs, run: ddev composer check-platform-reqs
  # Then add any missing ext-* entries to the require block in composer.json.
  log "running composer check-platform-reqs to detect missing ext-* requirements"
  # Composer exits non-zero when reqs are missing; we need stdout + continue to install-php-extensions.
  # Use --format=json: the default text output is a bordered table, so lines do not start with "ext-"
  # and awk patterns that assumed plain rows never matched (CI then skipped install-php-extensions).
  MISSING_EXTS=$( (COMPOSER_ALLOW_SUPERUSER=1 composer check-platform-reqs --format=json 2>/dev/null || true) \
    | jq -r '[.[] | select(.name | startswith("ext-")) | select(.status == "missing" or .status == "failed") | .name | sub("^ext-"; "")] | unique | .[]' 2>/dev/null) || true
  if [ -z "$MISSING_EXTS" ]; then
    log "no missing ext-* extensions reported by check-platform-reqs (or parse yielded empty)"
  else
    log "missing extensions from composer (names without ext- prefix): ${MISSING_EXTS//$'\n'/ }"
  fi

  # DRAINPIPE_PHP_EXTENSIONS can be set as a Bitbucket repository variable to
  # install extensions not declared in composer.json (e.g. proprietary agents).
  if [ -n "${DRAINPIPE_PHP_EXTENSIONS:-}" ]; then
    log "DRAINPIPE_PHP_EXTENSIONS is set (length $(printf '%s' "${DRAINPIPE_PHP_EXTENSIONS}" | wc -c) chars)"
  else
    log "DRAINPIPE_PHP_EXTENSIONS is unset"
  fi

  ALL_EXTS=$(printf '%s %s' "$MISSING_EXTS" "${DRAINPIPE_PHP_EXTENSIONS:-}" | xargs)
  if [ -n "$ALL_EXTS" ]; then
    log "install-php-extensions will run for: ${ALL_EXTS}"
    # shellcheck disable=SC2086
    install-php-extensions $ALL_EXTS
    log "install-php-extensions finished"
  else
    log "skipping install-php-extensions (no extensions to install)"
  fi

  log "configuring ~/.ssh and git identity for Drainpipe Bot"
  mkdir -p ~/.ssh && chmod 700 ~/.ssh
  echo "${ACQUIA_SSH_PRIVATE_KEY}" | base64 -d > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  if [ ! -s ~/.ssh/id_rsa ]; then
    log "warning: ~/.ssh/id_rsa is missing or empty after decode (check ACQUIA_SSH_PRIVATE_KEY)"
  else
    log "wrote ~/.ssh/id_rsa ($(wc -c < ~/.ssh/id_rsa) bytes)"
  fi
  git config --global user.name "Drainpipe Bot"
  git config --global user.email "no-reply@example.com"
fi

log "setup-php.sh finished"
