.drainpipe_setup_git:
  script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_USERNAME

.drainpipe_setup_ssh:
  script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - chmod 600 ~/.ssh/config
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
