# Updates a merge request description to include a table of composer lockfile
# changes.
drainpipe_composer_lock_diff:
  needs: []
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_MERGE_REQUEST_IID'
      changes:
        - composer.json
        - composer.lock
        - package-lock.json
  variables:
    GIT_STRATEGY: clone
  interruptible: false
  script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_USERNAME
    - apk add jq
    - composer global require davidrjonas/composer-lock-diff:^1.0
    - git fetch
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git merge $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --no-commit --no-ff
    - git reset .
    - composer global exec -- "composer-lock-diff --md > composer_lock_diff.md"
    - cat composer_lock_diff.md
    - |
      # Run package-lock.json diff if file exists
      if [ -f "package-lock.json" ]; then
        apk add nodejs npm
        npm install -g diff-lockfiles
        npx diff-lockfiles --markdown $CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD > package_lock_diff.md || echo "" > package_lock_diff.md
        cat package_lock_diff.md
      fi
    - |
      curl --fail -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID | jq '. | {id, iid, description}' > merge_request.json
    - sed -i 's/<!--Composer Lock Diff-->.*<!--\/Composer Lock Diff-->//g' merge_request.json
    - sed -i 's/<!--Package Lock Diff-->.*<!--\/Package Lock Diff-->//g' merge_request.json
    - |
      COMPOSER_DIFF_CONTENT=""
      if [ -s composer_lock_diff.md ]; then
        COMPOSER_DIFF_CONTENT=$(cat composer_lock_diff.md)
      fi
      PACKAGE_DIFF_CONTENT=""
      if [ -f package_lock_diff.md ] && [ -s package_lock_diff.md ]; then
        PACKAGE_DIFF_CONTENT=$(cat package_lock_diff.md)
      fi
      JSON=$(jq -c \
        --arg composer_diff "$COMPOSER_DIFF_CONTENT" \
        --arg package_diff "$PACKAGE_DIFF_CONTENT" \
        'if $composer_diff != "" then .description += "\n<!--Composer Lock Diff-->\n## Composer Lock Diff\n" + $composer_diff + "\n<!--/Composer Lock Diff-->" else . end |
         if $package_diff != "" then .description += "\n<!--Package Lock Diff-->\n## Package Lock Diff\n" + $package_diff + "\n<!--/Package Lock Diff-->" else . end' \
        merge_request.json)
      curl --fail -X PUT -d "$JSON" -H "Content-Type: application/json" -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID
