# Updates a merge request description to include a table of composer lockfile
# changes.
drainpipe_composer_lock_diff:
  needs: []
  rules:
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_MERGE_REQUEST_IID'
      changes:
        - composer.json
        - composer.lock
  variables:
    GIT_STRATEGY: clone
  interruptible: false
  script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_USERNAME
    - apk add jq
    - composer global require davidrjonas/composer-lock-diff:^1.0
    - git fetch
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git merge $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --no-commit --no-ff
    - git reset .
    - composer global exec -- "composer-lock-diff --md > composer_lock_diff.md"
    - cat composer_lock_diff.md
    - |
      curl --fail -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID | jq '. | {id, iid, description}' > merge_request.json
    - sed -i 's/<!--Composer Lock Diff-->.*<!--\/Composer Lock Diff-->//g' merge_request.json
    - |
      DIFF_CONTENT=""
      if [ -s composer_lock_diff.md ]; then
        DIFF_CONTENT=$(cat composer_lock_diff.md)
      fi
      JSON=$(jq -c \
        --arg diff "$DIFF_CONTENT" \
        'if $diff != "" then .description += "\n<!--Composer Lock Diff-->\n## Composer Lock Diff\n" + $diff + "\n<!--/Composer Lock Diff-->" else . end' \
        merge_request.json)
      curl --fail -X PUT -d "$JSON" -H "Content-Type: application/json" -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID
