# Updates a merge request description to include a table of composer lockfile
# changes.
drainpipe_composer_lock_diff:
  needs: []
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
  variables:
    GIT_STRATEGY: clone
  interruptible: false
  script:
    - git config --global user.email $GIT_EMAIL
    - git config --global user.name $GIT_USERNAME
    - apk add jq
    - composer global require davidrjonas/composer-lock-diff:^1.0
    - git fetch
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git merge $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME --no-commit --no-ff
    - git reset .
    - composer global exec -- "composer-lock-diff --md > composer_lock_diff.md"
    - cat composer_lock_diff.md
    - |
      curl --fail -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID | jq '. | {id, iid, description}' > merge_request.json
    - sed -i 's/<!--Composer Lock Diff-->.*<!--\/Composer Lock Diff-->//g' merge_request.json
    - |
      DESCRIPTION=$(cat merge_request.json | jq -r '.description' | sed -z 's/\n/\\n/g')
      if [ "$(cat composer_lock_diff.md)" != "" ]; then
        DIFF=$(cat composer_lock_diff.md | sed -z "s/\n/\\\n/g")
        DESCRIPTION="$DESCRIPTION\\n<!--Composer Lock Diff-->\\n## Composer Lock Diff\\n$DIFF\\n<!--/Composer Lock Diff-->"
      fi
      DESCRIPTION=$(echo $DESCRIPTION | sed 's/"/\\"/g')
      ID=$(cat merge_request.json | jq -r '.id')
      IID=$(cat merge_request.json | jq -r '.iid')
      JSON="{\"id\": $ID, \"iid\": $IID, \"description\": \"$DESCRIPTION\"}"
      curl --fail -X PUT -d "$JSON" -H "Content-Type: application/json" -H "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID

