image: webdevops/php-nginx:7.4-alpine

include:
  - local: '.drainpipe/gitlab/*.gitlab-ci.yml'
  - template: Verify/Browser-Performance.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  GIT_EMAIL: 'bot@example.com'
  GIT_USERNAME: 'Bot'
  PANTHEON_SITE_NAME: 'my-pantheon-site'
  PANTHEON_SITE_ID: 'some-long-string'
  PANTHEON_MULTIDEV_RUN_INSTALLER: 'true'
  REVIEW_APP_BASIC_AUTH: 'user:${REVIEW_APP_BASIC_AUTH_PASSWORD}@'
  # The following are set in project CI/CD variables
  #
  # https://pantheon.io/docs/machine-tokens
  # Use a bot account for this rather than an individual
  #PANTHEON_TERMINUS_TOKEN
  #
  # https://pantheon.io/docs/ssh-keys
  # No passphrase, add the public key to:
  # https://dashboard.pantheon.io/users/your-user-id#account/ssh-keys
  # Use a bot account for this rather than an individual
  #SSH_PRIVATE_KEY
  #
  # A password for http basic auth authentication on Multidev sites
  #REVIEW_APP_BASIC_AUTH_PASSWORD
  #
  # https://gitlab.com/username/project/-/settings/access_tokens
  # https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#project-access-tokens
  # Only supported by GitLab Premium or self-hosted GitLab
  # Needs "api" scope. Used by Composer Lock Diff.
  #GITLAB_ACCESS_TOKEN

cache:
  key:
    files:
      - composer.json
      - composer.lock
    prefix: $CI_JOB_NAME
  paths:
    - vendor/

.setup_node: &setup_node
  - apk add --update nodejs npm
  - npm install -g yarn

# Uncomment below if you want to customise the build or perform any actions
# after the Multidev environment has been deployed, or create a new job with
# "needs: [drainpipe_pantheon_drupal_review_app]"
#
#drainpipe_pantheon_drupal_review_app:
#  before_script:
#    - *setup_node
#  script:
#    - !reference [.drainpipe_pantheon_drupal_review_app, script]
#    - terminus lock:enable $PANTHEON_SITE_NAME.mr-$CI_MERGE_REQUEST_IID aba ${REVIEW_APP_BASIC_AUTH_PASSWORD} --yes

browser_performance:
  needs:
    - job: drainpipe_pantheon_drupal_review_app
      optional: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_EVENT_TYPE != "merge_train"'
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "schedule"'
  interruptible: true
  variables:
    URL: environment_url.txt
