.drainpipe_pantheon_drupal_review_app:
  script:
    - !reference [.drainpipe_pantheon_setup_terminus, script]
    - composer install
    - terminus multidev:delete $PANTHEON_SITE_NAME.mr-$CI_MERGE_REQUEST_IID --delete-branch --yes || true
    - |
      if [ "$PANTHEON_MULTIDEV_RUN_INSTALLER" == "true" ]; then
        terminus multidev:create $PANTHEON_SITE_NAME.dev mr-$CI_MERGE_REQUEST_IID --no-db --no-files --yes
      else
        terminus multidev:create $PANTHEON_SITE_NAME.dev mr-$CI_MERGE_REQUEST_IID --yes
      fi
    - ./vendor/bin/task build
    - ./vendor/bin/task snapshot:directory
    - ./vendor/bin/task deploy:git
    # Wait for Pantheon to sync
    - sleep 30
    - terminus aliases --only $PANTHEON_SITE_NAME --yes
    - |
      if [ "$PANTHEON_MULTIDEV_RUN_INSTALLER" == "true" ]; then
        ./vendor/bin/drush @$PANTHEON_SITE_NAME.mr-$CI_MERGE_REQUEST_IID --yes site:install --existing-config
      else
        ./vendor/bin/task site=@$PANTHEON_SITE_NAME.mr-$CI_MERGE_REQUEST_IID drupal:update
      fi
    - echo $CI_ENVIRONMENT_URL > environment_url.txt
drainpipe_pantheon_drupal_review_app:
  needs: []
  stage: deploy
  rules:
    # Don't run this on merge trains as it takes a long time
    - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merge_train"'
      when: never
    - if: '$CI_MERGE_REQUEST_IID'
  interruptible: true
  environment:
    name: review/$CI_MERGE_REQUEST_IID/drupal
    url: https://${REVIEW_APP_BASIC_AUTH}mr-$CI_MERGE_REQUEST_IID-$PANTHEON_SITE_NAME.pantheonsite.io
    on_stop: drainpipe_pantheon_stop_drupal_review_app
  variables:
    directory: /tmp/release
    branch: 'mr-${CI_MERGE_REQUEST_IID}'
    remote: 'ssh://codeserver.dev.${PANTHEON_SITE_ID}@codeserver.dev.${PANTHEON_SITE_ID}.drush.in:2222/~/repository.git'
    message: '${CI_COMMIT_MESSAGE}'
    site: '${PANTHEON_SITE_NAME}.mr-${CI_MERGE_REQUEST_IID}'
  script:
    - !reference [.drainpipe_pantheon_drupal_review_app, script]
  artifacts:
    paths:
      - environment_url.txt

drainpipe_pantheon_stop_drupal_review_app:
  stage: deploy
  rules:
    - if: '$CI_MERGE_REQUEST_IID'
      when: manual
  allow_failure: true
  environment:
    name: review/$CI_MERGE_REQUEST_IID/drupal
    action: stop
  variables:
    remote: '${PANTHEON_GIT_REMOTE}'
  script:
    - !reference [.drainpipe_pantheon_setup_terminus, script]
    - terminus multidev:delete $PANTHEON_SITE_NAME.mr-$CI_MERGE_REQUEST_IID --delete-branch --yes

drainpipe_pantheon_multidev_cleanup:
  needs: []
  resource_group: drainpipe_pantheon_multidev_cleanup
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  script:
    - !reference [.drainpipe_pantheon_setup_terminus, script]
    - apk add jq
    - |
      for LINE in $(curl -s --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/environments" | jq -r '.[] | "\(.id),\(.name)"'); do
        ID=$(echo $LINE | cut -f1 -d',')
        MR=$(echo $LINE | cut -f2 -d',' | cut -f2 -d'-')
        STATE=`curl -s --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR" | jq -r '.state'`
        if [ $STATE != "opened" ] && [ $MR != "development" ]; then
          echo "Deleting GitLab environment $ID for MR $MR"
          curl --request DELETE --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/environments/$ID"
        else
          echo "Ignoring GitLab environment $ID for MR $MR"
        fi
      done
      - |
        for MR in $(terminus multidev:list $PANTHEON_SITE_NAME --format json | jq -r .[].id | cut -d'-' -f2); do
          STATE=`curl -s --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR" | jq -r '.state'`
          if [ $STATE != "opened" ]; then
            echo "Deleting Pantheon Multidev for $MR"
            terminus --yes multidev:delete $PANTHEON_SITE_NAM.mr-$MR
          fi
        done
