version: '3'

tasks:
  git:
    desc: "Pushes a directory to a git remote"
    summary: |
      Given a directory, pushes it to a git remote whilst maintaining a linear
      history with the remote.

      usage: task deploy:git d="/tmp/release" b=main r="git@github.com:Lullabot/drainpipe.git" m="Initial commit" ge="bot@example.com" gn="Drainpipe Bot"

      directory=<directory>   A directory containing the files to be pushed
      branch=<branch>         Name of the branch to push to e.g. "main"
      remote=<remote>         Git remote to push to
      message=<message>       Commit message
      push=true               (optional) Push to the remote repository
    cmds:
      - if [ ! -d {{shellQuote .directory}} ] || [ "" == "{{.directory}}" ]; then echo "Please provide a path to a directory to deploy" && exit 1; fi
      - if [ "" == {{shellQuote .branch}} ]; then echo "Please provide a branch to deploy to" && exit 1; fi
      - if [ "" == {{shellQuote .remote}} ]; then echo "Please provide a remote git repository to push to" && exit 1; fi
      - if [ "" == {{shellQuote .message}} ]; then echo "Please provide a commit message" && exit 1; fi
      - |
        TMP_DIR=$(mktemp -d)
        (git clone --depth 1 --branch {{.branch}} {{.remote}} $TMP_DIR && cd $TMP_DIR) || true
        if [[ ! -d "$TMP_DIR/.git" ]]; then
          git clone --depth 1 {{.remote}} $TMP_DIR
          cd $TMP_DIR
          git checkout -b {{.branch}}
        fi
        mv $TMP_DIR/.git {{.directory}}
        cd {{.directory}}
        git checkout -B {{.branch}}
        git add -A
        git commit -m {{shellQuote .message}} --allow-empty
        git push origin {{.branch}}
        # Not using a bash-style comparison here due to https://github.com/go-task/task/issues/609
        {{if eq .push "true"}}git push origin {{.branch}}{{end}}
