version: '3'

tasks:
  actions:lint:
    desc: Run lint on Github Actions and Workflows
    preconditions:
      - sh: 'command -v action-validator'
        msg: "The action-validator package is not installed. Please run `yarn add @action-validator/cli` or `npm install -g @action-validator/core @action-validator/cli` to install it."
    summary: |
      Runs @action-validator/cli on GitHub Actions and Workflows

      usage: task github:actions:lint

      directories=<directories>   A list of directories seperated by spaces. Defaults to ".github/workflows .github/actions"
    cmds:
      - |
          directories=".github/workflows .github/actions"
          if [ "{{ .directories }}" != "" ]; then directories="{{ .directories }}"; fi
          find $directories -type f \( -iname '*.yaml' -o -iname '*.yml' \) | xargs -n1 action-validator
