version: '3'

tasks:
  actions:lint:
    desc: Run lint on Github Actions and Workflows
    summary: |
      Runs @action-validator/cli on GitHub Actions and Workflows

      usage: task github:actions:lint

      directories=<directories>   A list of directories seperated by spaces. Defaults to ".github/workflows .github/actions"
    cmds:
      - |
          directories=".github/workflows .github/actions"
          if [ "{{ .directories }}" != "" ]; then directories="{{ .directories }}"; fi

          if [ -f ./vendor/bin/action-validator ]; then
              find $directories -type f \( -iname '*.yaml' -o -iname '*.yml' \) | xargs -n1 ./vendor/bin/action-validator
          # Fallback for architectures that don't have a release e.g. Windows
          else
              yamls=$(find $directories -type f \( -iname '*.yaml' -o -iname '*.yml' \))
              action_validator_url_base="https://github.com/mpalmer/action-validator/releases/download/v0.6.0/action-validator_"
              action_validator_bin_path="/usr/local/bin/action-validator"
              [ "$(arch)" = "x86_64" ] && bin_name="linux_amd64"
              [ "$(arch)" = "aarch64" ] && bin_name="linux_arm64"
              curl -Lo $action_validator_bin_path "$action_validator_url_base$bin_name" || true
              chmod +x $action_validator_bin_path
              echo $yamls | xargs -n1 $action_validator_bin_path
          fi

  composer-lock-diff:
    desc: Runs composer-lock-diff on a pull request description and produces a new description
    summary: |
      Runs composer-lock-diff on a pull request description and produces a new description

      usage: task github:composer-lock-diff pull_request="pull_request.json" description_file="description.md"

      pull_request=<pull_request>   A file containing a json representation of a pull request from the GitHub API
      json_file              A file to write the new description to in a format which can be patched to GitHub directly
    cmds:
      - if [ "" == {{shellQuote .json_file}} ]; then echo "Please provide a file to write the description to" && exit 1; fi
      - composer global exec -- "composer-lock-diff --md > /tmp/drainpipe-composer-lock-diff"
      - defer: rm -f /tmp/drainpipe-composer-lock-diff
      - cp {{ .pull_request }} /tmp/drainpipe-composer-lock-diff-pr
      - defer: rm -f /tmp/drainpipe-composer-lock-diff-pr
      - |
        LOCK_DIFF="$(composer global exec -- "composer-lock-diff --md")"
        sed -i 's/<!--Composer Lock Diff-->.*<!--\/Composer Lock Diff-->//g' /tmp/drainpipe-composer-lock-diff-pr
        DESCRIPTION=$(cat /tmp/drainpipe-composer-lock-diff-pr | jq -r '.body')
        if [ "$(cat /tmp/drainpipe-composer-lock-diff)" != "" ]; then
            DIFF=$(cat /tmp/drainpipe-composer-lock-diff)
            DESCRIPTION="$DESCRIPTION
        <!--Composer Lock Diff-->
        ## Composer Lock Diff
        $DIFF
        <!--/Composer Lock Diff-->"
        fi
        DESCRIPTION=$(echo "$DESCRIPTION" | sed -z 's/\\/\\\\/g' | sed -z 's/\n/\\n/g' | sed -z 's/"/\\"/g' | sed -z 's/\r//g')
        echo "{\"body\": \"$(echo "$DESCRIPTION")\"}" > {{ .json_file }}
