version: '3'

tasks:
  compile:
    desc: Compiles/bundles JavaScript for custom themes and modules
    summary: |
      Compiles themes/custom/<theme name>/script.js in custom themes to
      themes/custom/<theme name>/script.min.js and modules/custom/<module name>/script.js
      to modules/custom/<module name>/script.js in custom modules.

      Requires esbuild, chokidar, and yargs
      Additionally if using Yarn 2+: @yarnpkg/esbuild-plugin-pnp

      usage: task javascript:compile DRAINPIPE_JAVASCRIPT_THEMES="my_custom_theme my_other_theme" DRAINPIPE_JAVASCRIPT_MODULES="my_module"
    cmds:
      - |
        ARGS="--minify"
        if [ "{{.args}}" != "" ]; then
          ARGS="{{.args}}"
        fi
        yarn node ./vendor/lullabot/drainpipe/config/esbuild.js --themes="{{.DRAINPIPE_JAVASCRIPT_THEMES}}" --modules="{{.DRAINPIPE_JAVASCRIPT_MODULES}}" $ARGS
  watch:
    desc: As compile, but continues running and watching for changes
    deps:
      - task: compile
        vars:
          args: "--watch"
