version: '3'

tasks:
  compile:
    desc: Compiles/bundles JavaScript for custom themes and modules
    summary: |
      Compiles themes/custom/<theme name>/script.js in custom themes to
      themes/custom/<theme name>/script.min.js and modules/custom/<module name>/script.js
      to modules/custom/<module name>/script.js in custom modules.

      Requires esbuild, chokidar, and yargs
      Additionally if using Yarn 2+: @yarnpkg/esbuild-plugin-pnp

      usage: task javascript:compile DRAINPIPE_JAVASCRIPT="web/themes/custom/script.js:web/themes/custom/script.min.js"
    cmds:
      - |
        ARGS="--minify"
        if [ "{{- .args -}}" != "" ]; then
          ARGS="{{- .args -}}"
        fi
        FILES="{{.DRAINPIPE_JAVASCRIPT | catLines | trim}}"
        COMMAND="yarn node ./vendor/lullabot/drainpipe/config/esbuild.js --files=\"$FILES\" $ARGS"
        echo "🪠 $COMMAND"
        eval $COMMAND
  watch:
    desc: As compile, but continues running and watching for changes
    deps:
      - task: compile
        vars:
          args: "--watch"
