version: '3'

tasks:
  compile:
    desc: |
      Compiles themes/custom/<theme name>/script.js in custom themes to
      themes/custom/<theme name>/script.min.js
    summary: |
      Requires: esbuild, chokidar, yargs
      Additionally if using Yarn 2+: @yarnpkg/esbuild-plugin-pnp

      usage: task javascript:compile themes="my_custom_theme my_other_theme"
    cmds:
      - yarn node ./vendor/lullabot/drainpipe/config/esbuild.js --themes="{{.themes}}" --minify
  watch:
    desc: |
      Compiles themes/custom/<theme name>/script.js in custom themes to
      themes/custom/<theme name>/script.min.js and watches for changes
    summary: |
      Requires: esbuild, chokidar, yargs
      Additionally if using Yarn 2+: @yarnpkg/esbuild-plugin-pnp

      usage: task javascript:watch themes="my_custom_theme my_other_theme"
    cmds:
      -  yarn node ./vendor/lullabot/drainpipe/config/esbuild.js --themes="{{.themes}}" --watch
