version: '3'

tasks:
  ssh:
    desc: "Configures SSH authentication"
    summary: |
      Sets up SSH key authentication using the following environment variables:

        usage: task setup:ssh

        SSH_PRIVATE_KEY   A private key whose public keypair has been added to
                          the remote service(s) we want to access
        SSH_KNOWN_HOSTS   The result of running "ssh-keyscan <domain>" of the
                          remove service(s) we want to access
    cmd:
      - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
      - cat ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
  git:
    desc: "Configures git to allow pushes to remotes"
    summary: |
      Configures git to allow pushes to remotes.

      git_email=<git email>   E-mail address to use for the git commit
      git_name=<git email>    Name to use for the git commit
    cmd:
      - git config user.email {{.git_email}}
      - git config user.name {{.git_name}}
