name: 'Configure ssh'
description: 'Configures SSH'
inputs:
  ssh-private-key:
    description: "SSH Private Key"
    required: true
  ssh-known-hosts:
    description: "SSH Known Hosts"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt install openssh-client
        eval $(ssh-agent -s)
        echo "${{ inputs.ssh-private-key }}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/config
        chmod 600 ~/.ssh/config
        if [ "{{ inputs.ssh-known-hosts}}" != "" ]; then
          echo "$ {{ inputs.ssh-known-hosts }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        fi
      shell: bash
