version: '3'

dotenv: ['.env']

includes:
  deploy: ./vendor/lullabot/drainpipe/tasks/deploy.yml
  drupal: ./vendor/lullabot/drainpipe/tasks/drupal.yml
  sass: ./vendor/lullabot/drainpipe/tasks/sass.yml
  snapshot: ./vendor/lullabot/drainpipe/tasks/snapshot.yml
  javascript: ./vendor/lullabot/drainpipe/tasks/javascript.yml
  test:
    taskfile: ./vendor/lullabot/drainpipe-dev/tasks/test.yml
    optional: true

output: prefixed
silent: true

#vars:
#  DRAINPIPE_SASS: |
#    web/themes/custom/mytheme/style.scss:web/themes/custom/mytheme/style.css
#  DRAINPIPE_JAVASCRIPT: |
#    web/themes/custom/mytheme/script.js:web/themes/custom/mytheme/script.min.js

tasks:
  build:
    desc: "Builds the project for production"
    deps: [drupal:composer:production]
    cmds:
      - echo "Nothing to do"
# assets:
#   desc: "Builds assets such as CSS & JS"
#   cmds:
#     - if [ -f "yarn.lock" ]; then yarn; else npm install; fi
#     - task: javascript:compile
#     - task: sass:compile
# assets:watch:
#   desc: "Builds assets such as CSS & JS, and watches them for changes"
#   deps: [sass:watch, javascript:watch]
