version: '3'

dotenv: ['.env', '.env.defaults']

includes:
  deploy: ./vendor/lullabot/drainpipe/tasks/deploy.yml
  drupal: ./vendor/lullabot/drainpipe/tasks/drupal.yml
  sass: ./vendor/lullabot/drainpipe/tasks/sass.yml
  snapshot: ./vendor/lullabot/drainpipe/tasks/snapshot.yml
  javascript: ./vendor/lullabot/drainpipe/tasks/javascript.yml
  test:
    taskfile: ./vendor/lullabot/drainpipe-dev/tasks/test.yml
    optional: true

output: prefixed
silent: true

#vars:
#  DRAINPIPE_SASS: |
#    web/themes/custom/mytheme/style.scss:web/themes/custom/mytheme/style.css
#  DRAINPIPE_JAVASCRIPT: |
#    web/themes/custom/mytheme/script.js:web/themes/custom/mytheme/script.min.js

tasks:
  build:
    desc: "Builds the project for production"
    deps: [drupal:composer:production]
    cmds:
      - echo "Nothing to do"
  site-schema:
    desc: Updates site-schema.yml with the latest schema in DB (update and post_update hooks).
    cmds:
      - ./vendor/bin/drush {{.site}} site-schema --format=yaml > site-schema.yml
  drupal:export:
    desc: The opposite of drupal:update, exports the site's configuration and schema to code.
    cmds:
      - composer update --lock
      - ./vendor/bin/drush {{.site}} --yes cache:clear plugin
      - ./vendor/bin/drush {{.site}} --yes updatedb --no-cache-clear
      - ./vendor/bin/drush {{.site}} --yes cache:rebuild
      - ./vendor/bin/drush {{.site}} --yes config:export
      - task: site-schema
# assets:
#   desc: "Builds assets such as CSS & JS"
#   cmds:
#     - if [ -f "yarn.lock" ]; then yarn; else npm install; fi
#     - task: javascript:compile
#     - task: sass:compile
# assets:watch:
#   desc: "Builds assets such as CSS & JS, and watches them for changes"
#   deps: [sass:watch, javascript:watch]
