name: 'Create a GitHub deployment'
description: 'Creates a GitHub deployment and echos the ID to the $GITHUB_ENV file'
inputs:
  github-token:
    description: "GitHub token as generated automatically in secrets.GITHUB_TOKEN"
    required: true
  environment:
    description: "The environment name"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/drainpipe/common/set-env

    - name: Create GitHub Deployment
      run: |
        echo "More debugging"
      shell: bash
