name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.sha }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Create release
        run: |
          gh release create ${GH_REF_NAME} \
            --title "${GH_REF_NAME}" \
            --notes "See https://github.com/Lullabot/drainpipe/releases/tag/${GH_REF_NAME}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REF_NAME: ${{ github.ref_name }}
