name: Repo Lockdown

on:
  issues:
    types: opened
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 0 * * 1'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-24.04
    steps:
      - uses: dessant/repo-lockdown@6e7465417db1c79a9c02df1797672f2bca97c926 # v4.0.0
        with:
          issue-comment: >
            Please file your issue in the upstream Drainpipe repository at https://github.com/Lullabot/drainpipe/issues.
          skip-closed-issue-comment: true
          pr-comment: >
            Please submit your pull request against the upstream Drainpipe repository at https://github.com/Lullabot/drainpipe/pulls.
            Note that the drainpipe-dev code is contained inside the root `/drainpipe-dev` directory.
          skip-closed-pr-comment: true
