name: 'Configure git'
description: 'Configures git username and e-mail address'
inputs:
  git-email:
    description: "Git e-mail address"
    required: true
  git-name:
    description: "Git name"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git config --global user.email ${GIT_EMAIL}
        git config --global user.name ${GIT_NAME}
      shell: bash
      env:
        GIT_EMAIL: ${{ inputs.git-email }}
        GIT_NAME: ${{ inputs.git-name }}
