name: 'Set Env'
description: 'Creates some useful environment variables'
inputs:
  github-api-token:
    description: "GitHub API token"
    required: true
  github-api-token-username:
    description: "GitHub API token username"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        echo "Setting Drainpipe environment variables:"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"

        if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
          # Get PR number for the current branch using gh
          DRAINPIPE_PR_NUMBER=$(gh pr list --state open --head "$GITHUB_REF_NAME" --json number --jq '.[0].number')
          DRAINPIPE_SHA=$(gh pr view "$DRAINPIPE_PR_NUMBER" --json headRefOid --jq '.headRefOid')
        else
          # Extract PR number from GITHUB_REF (for PR events)
          DRAINPIPE_PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          DRAINPIPE_SHA=$(cat $GITHUB_EVENT_PATH | jq -r .pull_request.head.sha)
        fi
        echo "DRAINPIPE_PR_NUMBER=$DRAINPIPE_PR_NUMBER" >> $GITHUB_ENV

        if [ -z "$DRAINPIPE_SHA" ] || [ "$DRAINPIPE_SHA" = "null" ]; then
          DRAINPIPE_SHA=$DRAINPIPE_PR_NUMBER
        fi
        echo "DRAINPIPE_SHA=$DRAINPIPE_SHA" >> $GITHUB_ENV

        echo "The variables have been set:"
        echo "DRAINPIPE_PR_NUMBER: $DRAINPIPE_PR_NUMBER"
        echo "DRAINPIPE_SHA: $DRAINPIPE_SHA"

      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
