name: 'Validate TERMINUS_TIMEOUT_LIMIT'
description: 'Validates and sets the TERMINUS_TIMEOUT_LIMIT environment variable'
runs:
  using: "composite"
  steps:
    - name: Validate TERMINUS_TIMEOUT_LIMIT
      run: |
        TIMEOUT_LIMIT="${{ vars.TERMINUS_TIMEOUT_LIMIT || '600' }}"
        if ! [[ "$TIMEOUT_LIMIT" =~ ^[0-9]+$ ]]; then
          echo "::error::TERMINUS_TIMEOUT_LIMIT must be a number. It represents the number of seconds that terminus will wait until timeout. Current value: $TIMEOUT_LIMIT"
          exit 1
        fi
        echo "TERMINUS_TIMEOUT_LIMIT=$TIMEOUT_LIMIT" >> $GITHUB_ENV
      shell: bash
