name: Push code to Acquia
description: Push code to the Acquia repository
inputs:
  repo-url:
    description: "Repository URL"
    required: true
  branch:
    description: "Which branch to push to"
    required: true
  commit-message:
    description: "Commit message"
    required: false
runs:
  using: composite
  steps:
    - name: Push code to Acquia
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec "task deploy:git directory=/tmp/release branch=${{ inputs.branch }} remote=${{ inputs.repo-url }} message=\"${{ inputs.commit-message }}\""
      shell: bash
