name: 'Sets the GitHub Deployment status'
description: 'Sets a GitHub deployment to success or failure'
inputs:
  github-token:
    description: "GitHub token as generated automatically in secrets.GITHUB_TOKEN"
    required: true
  environment-url:
    description: "The environment URL"
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/drainpipe/set-env

    - name: Set deployment to success
      run: |
        curl -f -H "Authorization: token ${{ inputs.github-token }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$GITHUB_DEPLOYMENT_ID/statuses -d "{\"state\":\"success\", \"environment_url\": \"${{ inputs.environment-url }}\"}"
      shell: bash

    - name: Set Deployment Failure Status
      run: |
        curl -f -H "Authorization: token ${{ inputs.github-token }}" -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$GITHUB_REPOSITORY/deployments/$GITHUB_DEPLOYMENT_ID/statuses -d "{\"state\":\"failure\"}"
      if: ${{ failure() }}
      shell: bash
