name: 'Prepare Pantheon Environment'
description: 'Sets up Terminus and authorises with Pantheon'
inputs:
  pantheon-token:
    description: "Pantheon Terminus Token"
    required: true
  terminus-plugins:
    description: "Terminus plugins"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        echo -e "Host *.drush.in\n    StrictHostKeyChecking no\n    HostkeyAlgorithms +ssh-rsa\n    PubkeyAcceptedAlgorithms +ssh-rsa" >> ~/.ssh/config
        mkdir ~/terminus
        curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.7/terminus.phar --output ~/terminus/terminus
        chmod +x ~/terminus/terminus
        ln -s ~/terminus/terminus /usr/local/bin/terminus
        echo "${{ inputs.terminus-plugins }}" | while read -d, plugin || [[ -n $plugin ]]; do terminus self:plugin:install $plugin; done
        terminus auth:login --machine-token="${{ inputs.pantheon-token }}"
      shell: bash
