version: '3.6'

services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: selenium/standalone-chrome:4.1.2-20220217
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=7903:7900
      - HTTPS_EXPOSE=7900:7900
    links:
      - web:web
      - web:drupal_chrome
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}

  firefox:
    container_name: ddev-${DDEV_SITENAME}-firefox
    image: selenium/standalone-firefox:4.1.2-20220217
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    expose:
      - 7900
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=7904:7900
      - HTTPS_EXPOSE=7901:7900
    links:
      - web:web
      - web:drupal_firefox
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
