#!/bin/bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -eux
echo "Building..."

./vendor/bin/task tugboat:build

./vendor/bin/task tugboat:update
