#!/bin/bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -eux
echo "Online..."

cd ${DOCROOT}/..
./vendor/bin/task online:tugboat
