#!/bin/bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -eux
echo "Online..."

#drainpipe-start
cd /var/www/html
#drainpipe-end
./vendor/bin/task online:tugboat
