name: 'Push code to Pantheon'
description: 'Pushes code to a Pantheon site'
inputs:
  terminus-token:
    description: "Pantheon Terminus Token"
    required: true
  site-name:
    description: "Pantheon site machine name"
    required: true
  branch:
    description: "Which branch to push to"
    required: true
  commit-message:
    description: "The commit message to use when pushing to Pantheon"
    required: true
runs:
  using: "composite"
  steps:
    - name: Trust all drush.in hosts
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec "echo -e \"Host *.drush.in\n    StrictHostKeyChecking no\n    HostkeyAlgorithms +ssh-rsa\n    PubkeyAcceptedKeyTypes +ssh-rsa\" >> ~/.ssh/config"
      shell: bash

    - name: Push to Pantheon
      run: |
        source .github/actions/drainpipe/set-env/bash_aliases
        drainpipe_exec terminus auth:login --machine-token="${TERMINUS_TOKEN}"
        SITE_ID=$(drainpipe_exec "terminus site:lookup ${SITE_NAME}")
        if [ "${BRANCH}" == "master" ]; then
          drainpipe_exec "terminus connection:set ${SITE_NAME}.dev git --yes"
        else
          drainpipe_exec "terminus connection:set ${SITE_NAME}.${BRANCH} git --yes"
        fi
        drainpipe_exec "./vendor/bin/task deploy:git directory=/tmp/release branch=${BRANCH} remote=ssh://codeserver.dev.$SITE_ID@codeserver.dev.$SITE_ID.drush.in:2222/~/repository.git message=\"${COMMIT_MESSAGE}\""
      shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        SITE_NAME: ${{ inputs.site-name }}
        TERMINUS_TOKEN: ${{ inputs.terminus-token }}
