name: Push Drainpipe Dev Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  Drainpipe-Dev:
    name: Push branch to drainpipe-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get information about the current branch
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Add drainpipe-dev deploy key in order to run git clone
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DRAINPIPE_DEV_DEPLOY_KEY }}
          log-public-key: false

      - name: Create git checkout of drainpipe-dev
        working-directory: drainpipe-dev
        run: |
          git init
          git remote add origin git@github.com:Lullabot/drainpipe-dev.git
          git fetch origin
          git reset --mixed origin/${{ github.ref_name }}
          git config user.email "no-reply@github.com"
          git config user.name "Drainpipe Bot"

      - name: Push branch commit to drainpipe-dev
        if: startsWith(github.ref, 'refs/heads/')
        working-directory: drainpipe-dev
        run: |
          git add -A
          git commit -m "${{ github.event.head_commit.message }}" --allow-empty
          git push origin ${{ github.ref_name }}

      - name: Push tag to drainpipe-dev
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: drainpipe-dev
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
