name: Push Drainpipe Dev Package

on:
  push:
    branches:
      - 460-drainpipe-dev-use-deploy-token
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.sha }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  Drainpipe-Dev:
    name: Push branch to drainpipe-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate application token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.DRAINPIPE_APP_ID }}
          private_key: ${{ secrets.DRAINPIPE_APP_PRIVATE_KEY }}

      - name: Add drainpipe-dev deploy key in order to run git clone
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DRAINPIPE_DEV_DEPLOY_KEY }}
          log-public-key: false

      # Commits made by the https://github.com/apps/lullabot-drainpipe application.
      # @see https://github.com/orgs/community/discussions/24664
      - name: Create git checkout of drainpipe-dev
        working-directory: drainpipe-dev
        run: |
          git init
          git branch -m ${{ github.ref_name }}
          git remote add origin git@github.com:Lullabot/drainpipe-dev.git
          git fetch origin
          git reset --mixed origin/${{ github.ref_name }}
          git config user.name "Lullabot-Drainpipe[bot]"
          git config user.email "157769597+Lullabot-Drainpipe[bot]@users.noreply.github.com"

      - name: Push branch to drainpipe-dev
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        uses: planetscale/ghcommit-action@v0.1.34
        with:
          repo: Lullabot/drainpipe-dev
          branch: ${{ github.ref_name }}
          commit_message: $COMMIT_MESSAGE
          empty: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          # Workaround if the commit message contains quotes.
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Push tag to drainpipe-dev
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        working-directory: drainpipe-dev
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}
