name: Push Drainpipe Dev Package

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

concurrency:
  group: drainpipe-dev
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  Drainpipe-Dev:
    name: Push to drainpipe-dev
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: ./scaffold/github/actions/common/setup-git
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com

      - name: Setup SSH
        uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd #v0.9.1
        with:
          ssh-private-key: ${{ secrets.DRAINPIPE_DEV_DEPLOY_KEY }}
          log-public-key: false

      - name: Create git checkout of drainpipe-dev
        working-directory: drainpipe-dev
        run: |
          git init
          git branch -m ${GH_REF_NAME}
          git remote add origin git@github.com:Lullabot/drainpipe-dev.git
          git fetch origin
        env:
          GH_REF_NAME: ${{ github.ref_name }}

      - name: Commit and push changes (Tag)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        working-directory: drainpipe-dev
        run: |
          git reset --mixed origin/main
          git add -A
          git commit -m "${GH_REF_NAME}" --allow-empty
          git tag ${GH_REF_NAME}
          git push origin refs/tags/${GH_REF_NAME}
        env:
          GH_REF_NAME: ${{ github.ref_name }}

      - name: Commit and push changes (Branch)
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        working-directory: drainpipe-dev
        run: |
          git reset --mixed origin/${GH_REF_NAME} || git reset --mixed origin/main
          git add -A
          git commit -m "${GH_MESSAGE}" --allow-empty
          git push origin refs/heads/${GH_REF_NAME}
        env:
          GH_REF_NAME: ${{ github.ref_name }}
          GH_MESSAGE: ${{ github.event.head_commit.message }}
