name: Push Drainpipe Dev Package

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  delete:

concurrency:
  group: drainpipe-dev-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  Drainpipe-Dev:
    name: Push to drainpipe-dev
    if: ${{ github.event_name != 'delete' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get branch information
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: For non-default branch and non-tags, check if drainpipe-dev was changed
        if: ${{ steps.branch-names.outputs.is_default == 'false' || steps.branch-names.outputs.is_tag == 'false' }}
        id: files-changed
        uses: tj-actions/changed-files@v44
        with:
          files: 'drainpipe-dev/**'

      - name: Add drainpipe-dev deploy key in order to run git clone
        if: ${{ steps.branch-names.outputs.is_default == 'true' || steps.branch-names.outputs.is_tag == 'true' || steps.files-changed.outputs.any_changed == 'true' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DRAINPIPE_DEV_DEPLOY_KEY }}
          log-public-key: false

      # Commits made by the https://github.com/apps/lullabot-drainpipe application.
      # @see https://github.com/orgs/community/discussions/24664
      - name: Create git checkout of drainpipe-dev
        if: ${{ steps.branch-names.outputs.is_default == 'true' || steps.branch-names.outputs.is_tag == 'true' || steps.files-changed.outputs.any_changed == 'true' }}
        working-directory: drainpipe-dev
        run: |
          git init
          git branch -m ${{ github.ref_name }}
          git remote add origin git@github.com:Lullabot/drainpipe-dev.git
          git fetch origin
          git reset --mixed origin/${{ github.ref_name }} || git reset --mixed origin/${{ steps.branch-names.outputs.default_branch }}
          git config user.name "Lullabot-Drainpipe[bot]"
          git config user.email "157769597+Lullabot-Drainpipe[bot]@users.noreply.github.com"

      - name: Push branch to drainpipe-dev
        working-directory: drainpipe-dev
        run: |
          git add -A
          git commit -m "$COMMIT_MESSAGE" --allow-empty
          git push origin ${{ github.ref_name }}
        env:
          # Workaround if the commit message contains quotes.
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

      - name: Push tag to drainpipe-dev
        if: ${{ steps.branch-names.outputs.is_tag == 'true' }}
        working-directory: drainpipe-dev
        run: |
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

  Drainpipe-Dev-Delete:
    name: Delete branch from drainpipe-dev
    if: ${{ github.event_name == 'delete' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add drainpipe-dev deploy key in order to run git clone
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DRAINPIPE_DEV_DEPLOY_KEY }}
          log-public-key: false

      # Todo could this check if the remote branch exists instead of just running this blindly?
      - name: Delete branch from drainpipe-dev
        run: |
          git clone git@github.com:Lullabot/drainpipe-dev.git
          git push --delete origin ${{ github.event.ref }} || true
