name: Test Production Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test-Production-Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: gd

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-


      - name: Install Drupal
        run: |
          cd ../
          composer create-project drupal/recommended-project drupal --ignore-platform-req=ext-gd
          cd drupal
          cp drainpipe/tests/fixtures/drainpipe-test-production-build/Taskfile.yml .
          composer config extra.drupal-scaffold.gitignore true
          composer config --json extra.drupal-scaffold.allowed-packages '["lullabot/drainpipe"]'
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.drupal/core-composer-scaffold true
          composer config --no-plugins allow-plugins.lullabot/drainpipe true
          composer config repositories.drainpipe --json '{"type": "path", "url": "../drainpipe", "options": {"symlink": false}}'
          composer config minimum-stability dev
          composer require "lullabot/drainpipe @dev" --with-all-dependencies

      - name: Run production build
        run: |
          cd ../drupal
          ./vendor/bin/task build

  Test-Production-Build-DDEV-Global-Binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: drainpipe

      - uses: ./drainpipe/scaffold/github/actions/common/set-env

      - name: Install DDEV
        uses: ./drainpipe/scaffold/github/actions/common/ddev
        with:
          git-name: Drainpipe Bot
          git-email: no-reply@example.com
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Setup Project
        run: |
          cp drainpipe/tests/fixtures/drainpipe-test-production-build/composer-ddev-global-binary.json composer.json
          cp drainpipe/tests/fixtures/drainpipe-test-production-build/Taskfile.yml .
          ddev config --project-type=drupal9
          ddev start
          ddev composer install
          # ddev won't create settings.ddev.php until settings.php exists.
          ddev config --project-type=drupal9
          ddev restart

      - name: Install Drupal
        run: |
          ddev drush site:install minimal -y
          echo "\$settings['config_sync_directory'] = '../config';" >> web/sites/default/settings.php
          ddev drush config:export -y

      - name: Run production build
        run: ddev task build
