name: "Test Composer Lock Diff"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Test-Composer-Lock-Diff:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        drupal-version: [ 10, 11 ]
    steps:
      - uses: actions/checkout@v4
        with:
          path: drainpipe

      - name: Setup build
        uses: ./drainpipe/.github/actions/setup-build
        with:
          composer-project: drupal/recommended-project:^${{ matrix.drupal-version }}

      - name: Commit current state
        run: |
          echo "/drainpipe" >> .gitignore
          git config --global user.email "no-reply@example.com"
          git config --global user.name "Drainpipe Bot"
          git init
          git add .
          git commit -m "Initial commit"

      - name: Install Composer Lock Diff
        run : ddev composer global require davidrjonas/composer-lock-diff:^1.0

      - name: Add a new package
        run: ddev composer require empty/empty:1.0

      - name: Run Composer Lock Diff on a Renovate PR
        run: |
          ddev task "github:composer-lock-diff pull_request='drainpipe/tests/fixtures/composer-lock-diff/github/renovate.json' json_file='renovate-processed.json'"
          if [ "$(cat renovate-processed.json)" != "$(cat drainpipe/tests/fixtures/composer-lock-diff/github/renovate-after.json)" ]; then
            echo "Expected description not produced"
            exit 1
          fi

      - name: Run Composer Lock Diff on a PR Template
        run: |
          ddev task "github:composer-lock-diff pull_request='drainpipe/tests/fixtures/composer-lock-diff/github/pr-template.json' json_file='pr-template-processed.json'"
          if [ "$(cat pr-template-processed.json)" != "$(cat drainpipe/tests/fixtures/composer-lock-diff/github/pr-template-after.json)" ]; then
            echo "Expected description not produced"
            exit 1
          fi

      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: processed-descriptions-${{ matrix.drupal-version }}
          path: |
            renovate-processed.json
            pr-template-processed.json
