name: "Test Docker in Docker in GitHub Actions"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Test-Dind:
    runs-on: ubuntu-latest
    container: justafish/ubuntu-ddev:latest
    steps:
      - name: Start DDEV
        run: |
          sudo service docker start
          find /var/lib/images/ -iname "*.tar" -o -iname "*.tar.xz" | xargs -r -P4 -i sudo docker load -i {}
          ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
          ddev start
