name: Test Binary Installer
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Test-Binary-Installer:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version: [ 8.1, 8.2, 8.3 ]
        include:
          - php-version: 8.1
            drupal-version: ":^10"
          - php-version: 8.2
            drupal-version: ":^10"
    steps:
      - name: Setup build
        uses: lullabot/drainpipe/.github/actions/setup-build
        with:
          composer-project: drupal/recommended-project${{ matrix.drupal-version }}
          php-version: ${{ matrix.php-version }}

      - name: Simulate failure
        run: |
          ddev exec touch /var/www/html/composer-cache/files/lullabot/drainpipe/bin/task/3.38.0/task_linux_amd64.tar
          ddev composer install

      - name: Test installing without composer cache
        run: |
          ddev composer install --no-cache
          test -x vendor/bin/task
          ddev composer install
          test -x vendor/bin/task
          rm -rf vendor
          ddev composer install
          test -x vendor/bin/task
          rm -rf vendor
          ddev composer install --no-cache
          test -x vendor/bin/task

      - name: Prove we can upgrade task within task
        run: |
          cp -a drainpipe/tests/fixtures/drainpipe-task-upgrade .
          cp -a drainpipe drainpipe-task-upgrade
          cd drainpipe-task-upgrade
          ddev start
          ddev composer install
          ddev task drupal:composer:development
          cp composer-upgraded.json composer.json
          cp composer-upgraded.lock composer.lock
          # Composer won't run updated plugin code until after its been
          # installed. Once we have two new releases after 3.11.0, that upgrade
          # task, we can remove this double call.
          ddev task drupal:composer:development || ddev task drupal:composer:development
