name: "Test Environment Variables"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Test-Env:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        drupal-version: [ 10, 11 ]
    steps:
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          composer-project: drupal/recommended-project:^${{ matrix.drupal-version }}

      - name: Copy test Taskfile
        run: |
          cp drainpipe/tests/fixtures/env/Taskfile.yml Taskfile.yml

      - name: Check files are created
        run: |
          test -f .env
          test -f .env.defaults

      - name: Check gitignore contains .env
        run: grep -q '.env' .gitignore

      - name: Test .env.defaults
        run: |
          echo "FOO=bar" >> .env.defaults
          ddev task bar
          # Not sure why Drupal needs restarting for this to work
          ddev restart
          DRUPAL_FOO_DEFAULT=$(ddev drush php:eval "print getenv('FOO')")
          echo "FOO=$DRUPAL_FOO_DEFAULT"
          if [ "$DRUPAL_FOO_DEFAULT" != "bar" ]; then exit 1; fi

      - name: Test overriding with .env
        run: |
          echo "FOO=baz" >> .env
          ddev task baz
          # Not sure why Drupal needs restarting for this to work
          ddev restart
          DRUPAL_FOO=$(ddev drush php:eval "print getenv('FOO')")
          echo "FOO=$DRUPAL_FOO"
          if [ "$DRUPAL_FOO" != "baz" ]; then exit 1; fi
