name: "Test Updating a PR"

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Test-Update-PR:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Curl
        run: |
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/PULL_NUMBER \
            -d '{"title":"new title","body":"updated body"}'
            --fail
