name: Valiate example Taskfile.yml
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Validate-Example-Taskfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npx ajv-cli validate -s taskfile-schema.json -d Taskfile.yml
