name: Validate example Tugboat configuration
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Validate-Example-Tugboat-Configuration:
    runs-on: ubuntu-22.04
    env:
      TUGBOAT_API_TOKEN: ${{ secrets.TUGBOAT_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: |
          curl -O https://dashboard.tugboatqa.com/cli/linux/tugboat.tar.gz
          tar xzvf tugboat.tar.gz
          declare | awk -F= '{print $1}'
          echo "Validating tugboat configuration..."
          ./tugboat validate scaffold/tugboat/config.example.yml
