name: Validate example Taskfile.yml
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: {}

jobs:
  Validate-Example-Taskfile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Validate Taskfile.yml
        run: |
          curl -sL https://taskfile.dev/install.sh | sh -s -- -d $(cat .taskfile) -b /usr/local/bin
          curl -O https://raw.githubusercontent.com/go-task/task/$(cat .taskfile)/website/src/public/schema.json
          npx ajv-cli validate -s schema.json -d scaffold/Taskfile.yml
